"use client"

import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import ClientComponents from "./components/ClientComponents";
import { Provider } from "react-redux";
import store from "./redux/store";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

const metadata: Metadata = {
  title: "summarist.wandag",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <Provider store={store}>
          <ClientComponents />
          {children}
        </Provider>
      </body>
    </html>
  );
}
